### ISSUE TITLE
Add always-on tab grouping by domain

### ISSUE THREAD

**Issue by kwilt** [asamuzaK/sidebarTabs#276]
_If possible_, could an option be added to the context menu under "Tab Group" to always group tabs by domain so that it does not need to be done manually from time to time?

**Comment by asamuzaK** [comment]
What you want to do is, when the tab itself moves to a different URL or opens a link in a new tab, automatically group the tabs that have the same domain as that new URL?

If that's the case, I don't think that option will provide a good user experience.

* If the newly opened URL is redirected to another location, the grouping process will be executed multiple times.
* If the new URL opens a popup, and the popup's URL is on a different domain, it will be opened in a completely different place instead of next to the opener tab.
