### ISSUE TITLE
Ability to move scrollbar to left side of sidebar (fx. when sidebar is moved to the left side of window)

### ISSUE THREAD

**Issue by ssssamstrup** [asamuzaK/sidebarTabs#320]
I would like the scrollbar to move to the left or the tabs in the sidebar, when the sidebar is shown on the left side of the browser.

Adding it as a manual switch to the left or right side, would also be fine (since I guess most people don't switch often).

Thank you for a great extension! Have been using it for a couple of years now.

ps: If it can be done with css and I should do it that way, please let me know how. I searched issues to find the css for it, but couldn't find a solution.

**Comment by asamuzaK** [comment]
If you set the writing direction to right-to-left using the CSS `direction` property, the scroll bar will appear on the left side.

I have not tested, but a user stylesheet like below should do the trick.

```` css
main {
  direction: rtl;
}
````

However, it is not recommended because it has side effects.
See [direction - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/direction)
